package com.example.quotes.staticdata;

import com.example.quotes.model.QuoteModel;

import java.util.Arrays;
import java.util.List;

public class QuoteData {
    public static List<QuoteModel> getQuotes() {
        return Arrays.asList(
                new QuoteModel("Whatever happens, take responsibility.", "Tony Robbins", false),
                new QuoteModel("Experience is simply the name we give our mistakes.", "Oscar Wilde", false),
                new QuoteModel("I think and that is all that I am.", "Wayne Dyer", false),
                new QuoteModel("A good plan today is better than a perfect plan tomorrow.", "Unknown", false),
                new QuoteModel("If the shoe doesn't fit, must we change the foot?", "Gloria Steinem", false),
                new QuoteModel("Each day provides its own gifts.", "Marcus Aurelius", false),
                new QuoteModel("While we stop to think, we often miss our opportunity.", "Publilius Syrus", false),
                new QuoteModel("Life isn't about finding yourself. Life is about creating yourself.", "Bernard Shaw", false),
                new QuoteModel("To bring anything into your life, imagine that it's already there.", "Richard Bach", false),
                new QuoteModel("Begin to weave and God will give you the thread.", "German proverb", false),
                new QuoteModel("The more you know yourself, the more you forgive yourself.", "Confucius", false),
                new QuoteModel("Someone remembers, someone cares; your name is whispered in someone's prayers.", "Unknown", false),
                new QuoteModel("Without faith, nothing is possible. With it, nothing is impossible.", "Mary Bethune", false),
                new QuoteModel("Once we accept our limits, we go beyond them.", "Albert Einstein", false),
                new QuoteModel("Don't be pushed by your problems; be led by your dreams.", "Unknown", false),
                new QuoteModel("Whatever we expect with confidence becomes our own self-fulfilling prophecy.", "Brian Tracy", false),
                new QuoteModel("Everything you can imagine is real.", "Pablo Picasso", false),
                new QuoteModel("Fear is a darkroom where negatives develop.", "Usman Asif", false),
                new QuoteModel("The truest wisdom is a resolute determination.", "Napoleon Bonaparte", false),
                new QuoteModel("Life is the flower for which love is the honey.", "Victor Hugo", false),
                new QuoteModel("Freedom is the right to live as we wish.", "Epictetus", false),
                new QuoteModel("Change your thoughts, change your life!", "Unknown", false),
                new QuoteModel("Never ignore a gut feeling, but never believe that it's enough.", "Robert Heller", false),
                new QuoteModel("Loss is nothing else but change, and change is Nature's delight.", "Marcus Aurelius", false),
                new QuoteModel("Someone is special only if you tell them.", "Byron Pulsifer", false),
                new QuoteModel("Today is the tomorrow you worried about yesterday.", "Unknown", false),
                new QuoteModel("There is no way to happiness, happiness is the way.", "Thich Nhat Hanh", false),
                new QuoteModel("The day always looks brighter from behind a smile.", "Unknown", false),
                new QuoteModel("A stumble may prevent a fall.", "Unknown", false),
                new QuoteModel("He who talks more is sooner exhausted.", "Lao Tzu", false),
                new QuoteModel("He who is contented is rich.", "Lao Tzu", false),
                new QuoteModel("What we achieve inwardly will change outer reality.", "Plutarch", false),
                new QuoteModel("Our strength grows out of our weaknesses.", "Ralph Waldo Emerson", false),
                new QuoteModel("We must become the change we want to see.", "Mahatma Gandhi", false),
                new QuoteModel("Happiness is found in doing, not merely possessing.", "Napoleon Hill", false),
                new QuoteModel("Put your future in good hands: your own.", "Unknown", false),
                new QuoteModel("We choose our destiny in the way we treat others.", "Wit", false),
                new QuoteModel("No snowflake in an avalanche ever feels responsible.", "Voltaire", false),
                new QuoteModel("Fortune favours the brave.", "Virgil", false),
                new QuoteModel("I believe in one thing only, the power of human will.", "Joseph Stalin", false),
                new QuoteModel("The best way out is always through.", "Robert Frost", false),
                new QuoteModel("The mind unlearns with difficulty what it has long learned.", "Seneca", false),
                new QuoteModel("I destroy my enemies when I make them my friends.", "Abraham Lincoln", false),
                new QuoteModel("No garden is without its weeds.", "Thomas Fuller", false),
                new QuoteModel("There is no failure except in no longer trying.", "Elbert Hubbard", false),
                new QuoteModel("Kind words will unlock an iron door.", "Turkish proverb", false),
                new QuoteModel("Problems are only opportunities with thorns on them.", "Hugh Miller", false),
                new QuoteModel("Life is just a chance to grow a soul.", "A. Powell Davies", false),
                new QuoteModel("Mountains cannot be surmounted except by winding paths.", "Johann Wolfgang von Goethe", false),
                new QuoteModel("May our heart's garden of awakening bloom with hundreds of flowers.", "Thich Nhat Hanh", false),
                new QuoteModel("Fortune befriends the bold.", "John Dryden", false),
                new QuoteModel("Keep true to the dreams of thy youth.", "Friedrich von Schiller", false),
                new QuoteModel("You're never a loser until you quit trying.", "Mike Ditka", false),
                new QuoteModel("Science is organized knowledge. Wisdom is organized life.", "Immanuel Kant", false),
                new QuoteModel("Knowing is not enough; we must apply!", "Johann Wolfgang von Goethe", false),
                new QuoteModel("Strong beliefs win strong men, and then make them stronger.", "Richard Bach", false),
                new QuoteModel("Autumn is a second spring when every leaf is a flower.", "Albert Camus", false),
                new QuoteModel("If you surrender to the wind, you can ride it.", "Toni Morrison", false),
                new QuoteModel("Keep yourself to the sunshine and you cannot see the shadow.", "Helen Keller", false),
                new QuoteModel("Write your plans in pencil and give God the eraser.", "Paulo Coelho", false),
                new QuoteModel("Inspiration exists, but it has to find us working.", "Pablo Picasso", false),
                new QuoteModel("Pick battles big enough to matter, small enough to win.", "Jonathan Kozol", false),
                new QuoteModel("Don't compromise yourself. You are all you've got.", "Janis Joplin", false),
                new QuoteModel("A short saying oft contains much wisdom.", "Sophocles", false),
                new QuoteModel("Difficulties are things that show a person what they are.", "Epictetus", false),
                new QuoteModel("When you doubt your power, you give power to your doubt.", "Honore de Balzac", false),
                new QuoteModel("The cause is hidden. The effect is visible to all.", "Ovid", false),
                new QuoteModel("A prudent question is one half of wisdom.", "Francis Bacon", false),
                new QuoteModel("The path to success is to take massive, determined action.", "Tony Robbins", false),
                new QuoteModel("I allow my intuition to lead my path.", "Manuel Puig", false),
                new QuoteModel("Nature takes away any faculty that is not used.", "William R. Inge", false),
                new QuoteModel("If you wish to be a writer, write.", "Epictetus", false),
                new QuoteModel("There is no way to prosperity, prosperity is the way.", "Wayne Dyer", false),
                new QuoteModel("Either you run the day or the day runs you.", "Jim Rohn", false),
                new QuoteModel("Better be ignorant of a matter than half know it.", "Publilius Syrus", false),
                new QuoteModel("Follow your instincts. That is where true wisdom manifests itself...", "Oprah Winfrey", false),
                new QuoteModel("If there is no struggle, there is no progress.", "Frederick Douglass", false),
                new QuoteModel("Where there is great love, there are always miracles.", "Willa Cather", false),
                new QuoteModel("Time you enjoy wasting, was not wasted.", "John Lennon", false),
                new QuoteModel("Every problem has a gift for you in its hands.", "Richard Bach", false),
                new QuoteModel("Sadness flies away on the wings of time.", "Jean de la Fontaine", false),
                new QuoteModel("I have often regretted my speech, never my silence.", "Publilius Syrus", false),
                new QuoteModel("Never put off till tomorrow what you can do today.", "Thomas Jefferson", false),
                new QuoteModel("Minds are like parachutes. They only function when open.", "Thomas Dewar", false),
                new QuoteModel("If a man does his best, what else is there?", "George Patton", false),
                new QuoteModel("The secret of success is constancy to purpose.", "Benjamin Disraeli", false),
                new QuoteModel("Life is a progress, and not a station.", "Ralph Emerson", false),
                new QuoteModel("All seasons are beautiful for the person who carries happiness within.", "Horace Friess", false),
                new QuoteModel("To avoid criticism, do nothing, say nothing, be nothing.", "Elbert Hubbard", false),
                new QuoteModel("All things change; nothing perishes.", "Ovid", false),
                new QuoteModel("Absence makes the heart grow fonder.", "Haynes Bayly", false),
                new QuoteModel("Imagination is the highest kite one can fly.", "Lauren Bacall", false),
                new QuoteModel("The beginning of knowledge is the discovery of something we do not understand.", "Frank Herbert", false),
                new QuoteModel("Love doesn't make the world go round, love is what makes the ride worthwhile.", "Elizabeth Browning", false),
                new QuoteModel("Whenever you have eliminated the impossible, whatever remains, however improbable, must be the truth.", "Arthur Conan Doyle", false),
                new QuoteModel("Good timber does not grow with ease; the stronger the wind, the stronger the trees.", "J. Willard Marriott", false),
                new QuoteModel("I believe that we are fundamentally the same and have the same basic potential.", "Dalai Lama", false),
                new QuoteModel("The winds and waves are always on the side of the ablest navigators.", "Edward Gibbon", false),
                new QuoteModel("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt", false),
                new QuoteModel("To get something you never had, you have to do something you never did.", "", false),
                new QuoteModel("Be thankful when you don't know something for it gives you the opportunity to learn.", "", false),
                new QuoteModel("Strength does not come from physical capacity. It comes from an indomitable will.", "Mahatma Gandhi", false),
                new QuoteModel("Each misfortune you encounter will carry in it the seed of tomorrow's good luck.", "Og Mandino", false),
                new QuoteModel("To forgive is to set a prisoner free and realize that prisoner was you.", "Lewis B. Smedes", false),
                new QuoteModel("In separateness lies the world's great misery, in compassion lies the world's true strength.", "Buddha", false),
                new QuoteModel("By believing passionately in something that does not yet exist, we create it.", "Nikos Kazantzakis", false),
                new QuoteModel("Letting go isn't the end of the world; it's the beginning of a new life.", "", false),
                new QuoteModel("All the great performers I have worked with are fuelled by a personal dream.", "John Eliot", false),
                new QuoteModel("One of the advantages of being disorderly is that one is constantly making exciting discoveries.", "A. A. Milne", false),
                new QuoteModel("I never see what has been done; I only see what remains to be done.", "Marie Curie", false),
                new QuoteModel("Begin at once to live and count each separate day as a separate life.", "Seneca", false),
                new QuoteModel("If you don't know where you are going, you will probably end up somewhere else.", "Lawrence Peter", false),
                new QuoteModel("It is not so important to know everything as to appreciate what we learn.", "Hannah More", false),
                new QuoteModel("The bird of paradise alights only upon the hand that does not grasp.", "John Berry", false),
                new QuoteModel("Think as a wise man but communicate in the language of the people.", "William Yeats", false),
                new QuoteModel("Practice yourself, for heaven's sake in little things, and then proceed to greater.", "Epictetus", false),
                new QuoteModel("If one does not know to which port is sailing, no wind is favorable.", "Seneca", false),
                new QuoteModel("Our greatest glory is not in never failing but rising every time we fall.", "", false),
                new QuoteModel("Being right is highly overrated. Even a stopped clock is right twice a day.", "", false),
                new QuoteModel("To be upset over what you don't have is to waste what you do have.", "Ken S. Keyes", false),
                new QuoteModel("If we did the things we are capable of, we would astound ourselves.", "Thomas Edison", false),
                new QuoteModel("Nothing in life is to be feared. It is only to be understood.", "Marie Curie", false),
                new QuoteModel("Successful people ask better questions, and as a result, they get better answers.", "Tony Robbins", false),
                new QuoteModel("Love is not blind; it simply enables one to see things others fail to see.", "", false),
                new QuoteModel("Life is a process. We are a process. The universe is a process.", "Anne Schaef", false),
                new QuoteModel("I think somehow we learn who we really are and then live with that decision.", "Eleanor Roosevelt", false),
                new QuoteModel("We learn what we have said from those who listen to our speaking.", "Kenneth Patton", false),
                new QuoteModel("A little knowledge that acts is worth infinitely more than much knowledge that is idle.", "Kahlil Gibran", false),
                new QuoteModel("If you get up one more time than you fall, you will make it through.", "", false),
                new QuoteModel("The doors we open and close each day decide the lives we live.", "Flora Whittemore", false),
                new QuoteModel("The worst bankrupt in the world is the person who has lost his enthusiasm.", "H. W. Arnold", false),
                new QuoteModel("Happiness comes when your work and words are of benefit to yourself and others.", "Buddha", false),
                new QuoteModel("Don't focus on making the right decision, focus on making the decision the right one.", "", false),
                new QuoteModel("The worst bankrupt in the world is the person who has lost his enthusiasm.", "H. W. Arnold", false),
                new QuoteModel("Happiness comes when your work and words are of benefit to yourself and others.", "Buddha", false),
                new QuoteModel("Don't focus on making the right decision, focus on making the decision the right one.", "", false),

                new QuoteModel("Success is not final, failure is not fatal: It is the courage to continue that counts.", "Winston Churchill", false),
                new QuoteModel("The only limit to our realization of tomorrow is our doubts of today.", "Franklin D. Roosevelt", false),
                new QuoteModel("Don't watch the clock; do what it does. Keep going.", "Sam Levenson", false),
                new QuoteModel("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt", false),
                new QuoteModel("Opportunities don't happen. You create them.", "Chris Grosser", false),
                new QuoteModel("It does not matter how slowly you go as long as you do not stop.", "Confucius", false),
                new QuoteModel("Everything you’ve ever wanted is on the other side of fear.", "George Addair", false),
                new QuoteModel("Hardships often prepare ordinary people for an extraordinary destiny.", "C.S. Lewis", false),
                new QuoteModel("Believe you can and you're halfway there.", "Theodore Roosevelt", false),
                new QuoteModel("The secret of getting ahead is getting started.", "Mark Twain", false),
                new QuoteModel("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis", false),
                new QuoteModel("I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson", false),
                new QuoteModel("If you can dream it, you can do it.", "Walt Disney", false),
                new QuoteModel("Success is the sum of small efforts, repeated day in and day out.", "Robert Collier", false),
                new QuoteModel("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "Roy T. Bennett", false),
                new QuoteModel("Do what you can with all you have, wherever you are.", "Theodore Roosevelt", false),
                new QuoteModel("The way to get started is to quit talking and begin doing.", "Walt Disney", false),
                new QuoteModel("Start where you are. Use what you have. Do what you can.", "Arthur Ashe", false),
                new QuoteModel("Dream big and dare to fail.", "Norman Vaughan", false),
                new QuoteModel("The harder you work for something, the greater you'll feel when you achieve it.", "", false),
                new QuoteModel("The only place where success comes before work is in the dictionary.", "Vidal Sassoon", false),
                new QuoteModel("Push yourself, because no one else is going to do it for you.", "", false),
                new QuoteModel("Don’t stop when you’re tired. Stop when you’re done.", "", false),
                new QuoteModel("Little things make big days.", "", false),
                new QuoteModel("It always seems impossible until it’s done.", "Nelson Mandela", false),
                new QuoteModel("Success doesn’t just find you. You have to go out and get it.", "", false),
                new QuoteModel("Great things never come from comfort zones.", "", false),
                new QuoteModel("Dream it. Wish it. Do it.", "", false),
                new QuoteModel("Success is what happens after you have survived all your mistakes.", "", false),
                new QuoteModel("The key to success is to focus on goals, not obstacles.", "", false),
                new QuoteModel("Wake up with determination. Go to bed with satisfaction.", "", false),
                new QuoteModel("Do something today that your future self will thank you for.", "", false),
                new QuoteModel("Don’t wait for opportunity. Create it.", "", false),
                new QuoteModel("Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", "", false),
                new QuoteModel("The difference between ordinary and extraordinary is that little extra.", "", false),
                new QuoteModel("The only way to achieve the impossible is to believe it is possible.", "", false),
                new QuoteModel("Doubt kills more dreams than failure ever will.", "", false),
                new QuoteModel("Work hard in silence. Let your success be the noise.", "", false),
                new QuoteModel("Don’t limit your challenges. Challenge your limits.", "", false),
                new QuoteModel("Success is not for the lazy.", "", false),
                new QuoteModel("The best time to plant a tree was 20 years ago. The second best time is now.", "", false),
                new QuoteModel("Don’t be afraid to give up the good to go for the great.", "John D. Rockefeller", false),
                new QuoteModel("If you want something you never had, you have to do something you’ve never done.", "", false),
                new QuoteModel("Motivation is what gets you started. Habit is what keeps you going.", "Jim Ryun", false),
                new QuoteModel("Don’t wish it were easier. Wish you were better.", "Jim Rohn", false),
                new QuoteModel("Go the extra mile. It’s never crowded.", "", false),
                new QuoteModel("Act as if what you do makes a difference. It does.", "William James", false),
                new QuoteModel("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau", false),
                new QuoteModel("Don’t be busy, be productive.", "", false),
                new QuoteModel("If you cannot do great things, do small things in a great way.", "Napoleon Hill", false),
                new QuoteModel("Nothing will work unless you do.", "Maya Angelou", false),
                new QuoteModel("It’s not about having time. It’s about making time.", "", false),
                new QuoteModel("The secret of success is to do the common thing uncommonly well.", "John D. Rockefeller Jr.", false)



                );
    }
}
